-- MySQL Script generated by MySQL Workbench
-- Thu Oct  1 19:14:44 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`TipoInstitucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoInstitucion` (
  `id_TipoInstitucion` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_TipoInstitucion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Convenio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Convenio` (
  `id_Convenio` INT NOT NULL AUTO_INCREMENT,
  `TipoInstitucion_id_TipoInstitucion` INT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `fecha_inicio` TIMESTAMP NOT NULL,
  `estado` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_Convenio`),
  INDEX `fk_Convenio_TipoInstitucion1_idx` (`TipoInstitucion_id_TipoInstitucion` ASC) VISIBLE,
  CONSTRAINT `fk_Convenio_TipoInstitucion1`
    FOREIGN KEY (`TipoInstitucion_id_TipoInstitucion`)
    REFERENCES `mydb`.`TipoInstitucion` (`id_TipoInstitucion`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Motivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Motivo` (
  `id_Motivo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Motivo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estado` (
  `id_Estado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Estado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Paciente` (
  `id_Paciente` INT NOT NULL AUTO_INCREMENT,
  `Estado_id_Estado` INT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `nombre_social` VARCHAR(45) NOT NULL,
  `pronombre` VARCHAR(45) NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `intentos_contacto` INT NOT NULL DEFAULT 0,
  `fecha_ingreso` TIMESTAMP NOT NULL,
  `rut` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Paciente`),
  INDEX `fk_Paciente_Estado1_idx` (`Estado_id_Estado` ASC) VISIBLE,
  UNIQUE INDEX `rut_UNIQUE` (`rut` ASC) VISIBLE,
  CONSTRAINT `fk_Paciente_Estado1`
    FOREIGN KEY (`Estado_id_Estado`)
    REFERENCES `mydb`.`Estado` (`id_Estado`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Derivacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Derivacion` (
  `id_Derivacion` INT NOT NULL AUTO_INCREMENT,
  `Convenio_id_Convenio` INT NULL,
  `Motivo_id_Motivo` INT NOT NULL,
  `Paciente_id_Paciente` INT NOT NULL,
  PRIMARY KEY (`id_Derivacion`, `Motivo_id_Motivo`, `Paciente_id_Paciente`),
  INDEX `fk_Derivacion_Convenio1_idx` (`Convenio_id_Convenio` ASC) VISIBLE,
  INDEX `fk_Derivacion_Motivo1_idx` (`Motivo_id_Motivo` ASC) VISIBLE,
  INDEX `fk_Derivacion_Paciente1_idx` (`Paciente_id_Paciente` ASC) VISIBLE,
  CONSTRAINT `fk_Derivacion_Convenio1`
    FOREIGN KEY (`Convenio_id_Convenio`)
    REFERENCES `mydb`.`Convenio` (`id_Convenio`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Derivacion_Motivo1`
    FOREIGN KEY (`Motivo_id_Motivo`)
    REFERENCES `mydb`.`Motivo` (`id_Motivo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Derivacion_Paciente1`
    FOREIGN KEY (`Paciente_id_Paciente`)
    REFERENCES `mydb`.`Paciente` (`id_Paciente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Coordinador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Coordinador` (
  `id_Coordinador` INT NOT NULL AUTO_INCREMENT,
  `Convenio_id_Convenio` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Coordinador`, `Convenio_id_Convenio`),
  INDEX `fk_Coordinador_Convenio1_idx` (`Convenio_id_Convenio` ASC) VISIBLE,
  CONSTRAINT `fk_Coordinador_Convenio1`
    FOREIGN KEY (`Convenio_id_Convenio`)
    REFERENCES `mydb`.`Convenio` (`id_Convenio`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Accion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Accion` (
  `id_Accion` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Accion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TipoUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoUsuario` (
  `id_TipoUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_TipoUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `id_Usuario` INT NOT NULL AUTO_INCREMENT,
  `TipoUsuario_id_TipoUsuario` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `nombre_social` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(225) NOT NULL,
  PRIMARY KEY (`id_Usuario`, `TipoUsuario_id_TipoUsuario`),
  INDEX `fk_Usuario_TipoUsuario1_idx` (`TipoUsuario_id_TipoUsuario` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_TipoUsuario1`
    FOREIGN KEY (`TipoUsuario_id_TipoUsuario`)
    REFERENCES `mydb`.`TipoUsuario` (`id_TipoUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Log` (
  `id_Log` INT NOT NULL AUTO_INCREMENT,
  `Accion_id_Accion` INT NOT NULL,
  `Usuario_id_Usuario` INT NULL,
  `Convenio_id_Convenio` INT NULL,
  `Derivacion_id_Derivacion` INT NULL,
  `entidad` VARCHAR(45) NOT NULL,
  `atributo` VARCHAR(45) NOT NULL,
  `valor_antes` VARCHAR(45) NULL,
  `valor_despues` VARCHAR(45) NULL,
  `fecha` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id_Log`, `Accion_id_Accion`),
  INDEX `fk_Log_Accion_idx` (`Accion_id_Accion` ASC) VISIBLE,
  INDEX `fk_Log_Usuario1_idx` (`Usuario_id_Usuario` ASC) VISIBLE,
  INDEX `fk_Log_Convenio1_idx` (`Convenio_id_Convenio` ASC) VISIBLE,
  INDEX `fk_Log_Derivacion1_idx` (`Derivacion_id_Derivacion` ASC) VISIBLE,
  CONSTRAINT `fk_Log_Accion`
    FOREIGN KEY (`Accion_id_Accion`)
    REFERENCES `mydb`.`Accion` (`id_Accion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Log_Usuario1`
    FOREIGN KEY (`Usuario_id_Usuario`)
    REFERENCES `mydb`.`Usuario` (`id_Usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Log_Convenio1`
    FOREIGN KEY (`Convenio_id_Convenio`)
    REFERENCES `mydb`.`Convenio` (`id_Convenio`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Log_Derivacion1`
    FOREIGN KEY (`Derivacion_id_Derivacion`)
    REFERENCES `mydb`.`Derivacion` (`id_Derivacion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Politica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Politica` (
  `id_Politica` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Politica`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Permiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Permiso` (
  `id_Permiso` INT NOT NULL AUTO_INCREMENT,
  `TipoUsuario_id_TipoUsuario` INT NOT NULL,
  `Politica_id_Politica` INT NOT NULL,
  PRIMARY KEY (`id_Permiso`, `TipoUsuario_id_TipoUsuario`, `Politica_id_Politica`),
  INDEX `fk_Permiso_TipoUsuario1_idx` (`TipoUsuario_id_TipoUsuario` ASC) VISIBLE,
  INDEX `fk_Permiso_Politica1_idx` (`Politica_id_Politica` ASC) VISIBLE,
  CONSTRAINT `fk_Permiso_TipoUsuario1`
    FOREIGN KEY (`TipoUsuario_id_TipoUsuario`)
    REFERENCES `mydb`.`TipoUsuario` (`id_TipoUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Permiso_Politica1`
    FOREIGN KEY (`Politica_id_Politica`)
    REFERENCES `mydb`.`Politica` (`id_Politica`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Contacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Contacto` (
  `id_Contacto` INT NOT NULL AUTO_INCREMENT,
  `Paciente_id_Paciente` INT NOT NULL,
  `encargado` VARCHAR(45) NOT NULL,
  `fecha` TIMESTAMP NOT NULL,
  `respuesta` VARCHAR(45) NOT NULL,
  `descripcion` TEXT NULL,
  PRIMARY KEY (`id_Contacto`, `Paciente_id_Paciente`),
  INDEX `fk_Contacto_Paciente1_idx` (`Paciente_id_Paciente` ASC) VISIBLE,
  CONSTRAINT `fk_Contacto_Paciente1`
    FOREIGN KEY (`Paciente_id_Paciente`)
    REFERENCES `mydb`.`Paciente` (`id_Paciente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Psicopatologia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Psicopatologia` (
  `id_Psicopatologia` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Psicopatologia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Diagnostico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Diagnostico` (
  `id_Diagnostico` INT NOT NULL AUTO_INCREMENT,
  `Paciente_id_Paciente` INT NOT NULL,
  `Psicopatologia_id_Psicopatologia` INT NOT NULL,
  PRIMARY KEY (`id_Diagnostico`, `Paciente_id_Paciente`, `Psicopatologia_id_Psicopatologia`),
  INDEX `fk_Diagnostico_Paciente1_idx` (`Paciente_id_Paciente` ASC) VISIBLE,
  INDEX `fk_Diagnostico_Psicopatologia1_idx` (`Psicopatologia_id_Psicopatologia` ASC) VISIBLE,
  CONSTRAINT `fk_Diagnostico_Paciente1`
    FOREIGN KEY (`Paciente_id_Paciente`)
    REFERENCES `mydb`.`Paciente` (`id_Paciente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Diagnostico_Psicopatologia1`
    FOREIGN KEY (`Psicopatologia_id_Psicopatologia`)
    REFERENCES `mydb`.`Psicopatologia` (`id_Psicopatologia`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Protocolo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Protocolo` (
  `id_Protocolo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Protocolo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Atencion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Atencion` (
  `id_Atencion` INT NOT NULL AUTO_INCREMENT,
  `Paciente_id_Paciente` INT NOT NULL,
  `Protocolo_id_Protocolo` INT NULL,
  `fecha` TIMESTAMP NOT NULL,
  `terapeuta` VARCHAR(45) NOT NULL,
  `aplica_protocolo` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_Atencion`, `Paciente_id_Paciente`),
  INDEX `fk_Atencion_Paciente1_idx` (`Paciente_id_Paciente` ASC) VISIBLE,
  INDEX `fk_Atencion_Protocolo1_idx` (`Protocolo_id_Protocolo` ASC) VISIBLE,
  CONSTRAINT `fk_Atencion_Paciente1`
    FOREIGN KEY (`Paciente_id_Paciente`)
    REFERENCES `mydb`.`Paciente` (`id_Paciente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Atencion_Protocolo1`
    FOREIGN KEY (`Protocolo_id_Protocolo`)
    REFERENCES `mydb`.`Protocolo` (`id_Protocolo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
